CREATE OR REPLACE DATABASE fred_financial_data;
CREATE OR REPLACE SCHEMA fred_financial_data.market_indices;
USE DATABASE fred_financial_data;
USE SCHEMA market_indices;


SELECT * FROM FRED_INDEX_DATA ;

SELECT DISTINCT INDEX_NAME FROM FRED_INDEX_DATA;


-- Create RAW_FRED schema
CREATE SCHEMA IF NOT EXISTS RAW_FRED;

-- Create staging table
CREATE TABLE IF NOT EXISTS RAW_FRED.RAW_FRED_STAGING (
    DATE DATE,
    INDEX_NAME STRING,
    CLOSE FLOAT
    -- Add more columns if needed
);


CREATE SCHEMA IF NOT EXISTS RAW_DOW30;



-- Create the staging table for raw data
CREATE TABLE IF NOT EXISTS RAW_DOW30_STAGING (
    DATE DATE,
    INDEX_NAME STRING,
    CLOSE FLOAT
);


SHOW DATABASES LIKE 'FRED_FINANCIAL_DATA';
SHOW SCHEMAS IN DATABASE fred_financial_data;
SHOW TABLES IN SCHEMA RAW_DOW30;


USE DATABASE FRED_FINANCIAL_DATA;

USE SCHEMA RAW_DOW30;

SHOW TABLES IN SCHEMA RAW_DOW30;


SELECT * FROM RAW_DOW30.RAW_DOW30_STAGING DESC;

-- Step 1: Create a stream on the staging table
CREATE OR REPLACE STREAM RAW_DOW30_STREAM 
ON TABLE RAW_DOW30.RAW_DOW30_STAGING;

USE DATABASE FRED_FINANCIAL_DATA;
USE SCHEMA RAW_DOW30;

CREATE OR REPLACE STREAM RAW_DOW30_STREAM 
ON TABLE RAW_DOW30.RAW_DOW30_STAGING;
USE DATABASE FRED_FINANCIAL_DATA;
USE SCHEMA RAW_DOW30;
CREATE OR REPLACE STREAM RAW_DOW30_STREAM 
ON TABLE RAW_DOW30.RAW_DOW30_STAGING;
SHOW STREAMS;
SELECT * FROM RAW_DOW30_STREAM;
