-- manage_env.j2
-- Jinja template to configure Snowflake environment dynamically

USE ROLE PROD_ROLE;
USE WAREHOUSE PROD_WH;
USE DATABASE PROD_DB;
USE SCHEMA PROD_SCHEMA;

CREATE TABLE IF NOT EXISTS PROD_SCHEMA.SAMPLE_TABLE (
    ID INTEGER AUTOINCREMENT,
    NAME STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    GRANT SELECT ON TABLE PROD_SCHEMA.SAMPLE_TABLE TO ROLE READ_ONLY_ROLE;
